version: '2'
services:
  data:
    image: debian:jessie
    volumes:
      - ./data/media:/srv/data/media
      - /var/www/static
      - ./data/backup:/srv/data/backup
      - ./data/log:/var/log

  web:
    build: src
    command: /bin/sh /src/scripts/start_web.sh
    volumes:
      - ./src:/src
    volumes_from:
      - data
    ports:
      - "9000:9000"
    expose:
      - "8000"
    links:
      - db
    environment:
      - DEBUG='true'
      - EMAIL_HOST=localhost
      - EMAIL_PORT=1025

  db:
    image: postgres:9.5.2
    volumes_from:
      - data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=pgdata

  nginx:
    image: nginx
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/log/nginx/:/var/log/nginx
    ports:
      - "80:80"
    volumes_from:
      - data
    links:
      - web
