# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Observatory', models.CharField(max_length=200)),
                ('Data_year', models.CharField(max_length=200)),
                ('agglomeration', models.CharField(max_length=200)),
                ('Zone_complementaire', models.CharField(max_length=200)),
                ('Type_habitat', models.CharField(max_length=200)),
                ('epoque_construction_homogene', models.CharField(max_length=200)),
                ('anciennete_locataire_homogene', models.CharField(max_length=200)),
                ('nombre_pieces_homogene', models.CharField(max_length=200)),
                ('loyer_1_decile', models.CharField(max_length=200)),
                ('loyer_1_quartile', models.CharField(max_length=200)),
                ('loyer_median', models.CharField(max_length=200)),
                ('loyer_3_quartile', models.CharField(max_length=200)),
                ('loyer_9_decile', models.CharField(max_length=200)),
                ('loyer_moyen', models.CharField(max_length=200)),
                ('loyer_mensuel_1_decile', models.CharField(max_length=200)),
                ('loyer_mensuel_1_quartile', models.CharField(max_length=200)),
                ('loyer_mensuel_median', models.CharField(max_length=200)),
                ('loyer_mensuel_3_quartile', models.CharField(max_length=200)),
                ('loyer_mensuel_9_decile', models.CharField(max_length=200)),
                ('moyenne_loyer_mensuel', models.CharField(max_length=200)),
                ('surface_moyenne', models.CharField(max_length=200)),
                ('nombre_obsservations', models.CharField(max_length=200)),
                ('nombre_logements', models.CharField(max_length=200)),
                ('methodologie_production', models.CharField(max_length=200)),
            ],
        ),
    ]
