# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:28
from __future__ import unicode_literals

from django.db import migrations


def convert_type(apps, schema_editor):
    Loyer = apps.get_model("loyers", "Loyer")
    loyers = Loyer.objects.all()
    for loyer in loyers:
        loyer.Data_year = int(loyer.Data_year)
        if loyer.loyer_1_decile is not '':
            loyer.loyer_1_decile = float(loyer.loyer_1_decile.replace(',', '.'))
        else:
            loyer.loyer_1_decile = 0
        if loyer.loyer_1_quartile is not '':
            loyer.loyer_1_quartile = float(loyer.loyer_1_quartile.replace(',', '.'))
        else:
            loyer.loyer_1_quartile = 0
        if loyer.loyer_median is not '':
            loyer.loyer_median = float(loyer.loyer_median.replace(',', '.'))
        else:
            loyer.loyer_median = 0
        if loyer.loyer_3_quartile is not '':
            loyer.loyer_3_quartile = float(loyer.loyer_3_quartile.replace(',', '.'))
        else:
            loyer.loyer_3_quartile = 0
        if loyer.loyer_9_decile is not '':
            loyer.loyer_9_decile = float(loyer.loyer_9_decile.replace(',', '.'))
        else:
            loyer.loyer_9_decile = 0
        if loyer.loyer_moyen is not '':
            loyer.loyer_moyen = float(loyer.loyer_moyen.replace(',', '.'))
        else:
            loyer.loyer_moyen = 0
        loyer.save()


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0002_auto_20160709_0837'),
    ]

    operations = [
    	migrations.RunPython(convert_type, reverse_func),
    ]
