# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:50
from __future__ import unicode_literals

from django.db import migrations

def consolidate_number_of_rooms(apps, schema_editor):
    NumberOfRooms = apps.get_model("loyers", "NumberOfRooms")
    number_of_rooms = NumberOfRooms.objects.all()
    for nb_of_rooms in number_of_rooms:
        nb_of_rooms.name = nb_of_rooms.name.replace('Maison ', '')
        nb_of_rooms.name = nb_of_rooms.name.replace('Appart ', '')
        nb_of_rooms.name = nb_of_rooms.name.replace('Ensemble ', '')
        nb_of_rooms.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0009_auto_20160710_1233'),
    ]

    operations = [
        migrations.RunPython(consolidate_number_of_rooms, reverse_func),
    ]
