# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0003_auto_20160709_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyer',
            name='Data_year',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_1_decile',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_1_quartile',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_3_quartile',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_9_decile',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_median',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_mensuel_1_decile',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_mensuel_1_quartile',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_mensuel_3_quartile',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_mensuel_9_decile',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_mensuel_median',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='loyer_moyen',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='moyenne_loyer_mensuel',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='nombre_logements',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='nombre_obsservations',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loyer',
            name='surface_moyenne',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
