# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0004_auto_20160710_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agglomeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AgglomerationDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMethodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RenterSeniority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='loyer',
            name='agglomeration_description_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.AgglomerationDescription'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='agglomeration_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.Agglomeration'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='construction_period_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.ConstructionPeriod'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='housing_type_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.HousingType'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='number_of_rooms_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.NumberOfRooms'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='observatory_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.Observatory'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='production_methodology_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.ProductionMethodology'),
        ),
        migrations.AddField(
            model_name='loyer',
            name='renter_seniority_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loyers.RenterSeniority'),
        ),
    ]
