# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:33
from __future__ import unicode_literals

from django.db import migrations


def consolidate_house_type(apps, schema_editor):
    Loyer = apps.get_model("loyers", "Loyer")
    HousingType = apps.get_model("loyers", "HousingType")
    ensemble, created = HousingType.objects.get_or_create(name="Ensemble")
    maison = HousingType.objects.get(name="Maison")
    appartement = HousingType.objects.get(name="Appartement")
    loyers = Loyer.objects.all()
    # number_of_rooms Maison, Ensemble, Appart =>
    # fill housing_type
    for loyer in loyers:
        if loyer.number_of_rooms is None:
            #if loyer.housing_type is None:
            #    loyer.housing_type = ensemble
            pass
        elif loyer.number_of_rooms.name.startswith('Maison'):
            loyer.housing_type = maison
        elif loyer.number_of_rooms.name.startswith('Appart'):
            loyer.housing_type = appartement
        elif loyer.number_of_rooms.name.startswith('Ensemble'):
            #loyer.housing_type = ensemble
            pass
        loyer.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0008_auto_20160710_1133'),
    ]

    operations = [
        migrations.RunPython(consolidate_house_type, reverse_func),
    ]
