# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:25
from __future__ import unicode_literals

from django.db import migrations

# clean 'ALL' (paris only in 2014)
def merge_number_of_rooms(apps, schema_editor):
    Loyer = apps.get_model("loyers", "Loyer")
    AgglomerationDescription = apps.get_model("loyers", "AgglomerationDescription")
    HousingType = apps.get_model("loyers", "HousingType")
    ConstructionPeriod = apps.get_model("loyers", "ConstructionPeriod")
    RenterSeniority = apps.get_model("loyers", "RenterSeniority")
    loyers = Loyer.objects.all()
    for loyer in loyers:
        if loyer.agglomeration_description and loyer.agglomeration_description.name == 'ALL':
            loyer.agglomeration_description = None
        if loyer.housing_type and loyer.housing_type.name == 'ALL':
            loyer.housing_type = None
        if loyer.construction_period and loyer.construction_period.name == 'ALL':
            loyer.construction_period = None
        if loyer.renter_seniority and loyer.renter_seniority.name == 'ALL':
            loyer.renter_seniority = None
        loyer.save()
    AgglomerationDescription.objects.get(name="ALL").delete()
    HousingType.objects.get(name="ALL").delete()
    ConstructionPeriod.objects.get(name="ALL").delete()
    RenterSeniority.objects.get(name="ALL").delete()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('loyers', '0011_auto_20160710_1302'),
    ]

    operations = [
        migrations.RunPython(merge_number_of_rooms, reverse_func),
    ]
